DELETE http://localhost:2000/players/76561198126908199

###
POST localhost:2000/players
Content-Type: application/json

{
  "playerID": "76561198126908199",
  "steamID": "76561198126908199",
  "name": "SHI3LD",
  "teamID": "1",
  "squadID": null
}
