/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: VsyLFjEm6XPx0ycZpqh1kP2r5y+ShbtY7QufpIiXBRbXFJnM2oKcNBTzAMsz0EzXRV2xiyXi1rQHDaYzouBvgw==
 */

/* eslint-disable */
// tslint:disable

type ManagedMessageType = 'player_joined' | 'server_status' | 'session_ended' | 'session_started' | 'sign_up';
export type {ManagedMessageType}
