/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: os0QrBycY0ywCFAbLx5yzQFqRj6ln8cD9Sgkg0HP0HzI2RmVNnnTo43wnn1oGac2dvU2eCchpriapqbkUyrmEA==
 */

/* eslint-disable */
// tslint:disable

import ManagedMessage, {ManagedMessage_InsertParameters} from './managed_message'
import Player, {Player_InsertParameters} from './player'
import SeedLog, {SeedLog_InsertParameters} from './seed_log'
import SeedSessionLog, {SeedSessionLog_InsertParameters} from './seed_session_log'
import Seeder, {Seeder_InsertParameters} from './seeder'
import Server, {Server_InsertParameters} from './server'
import Tenant, {Tenant_InsertParameters} from './tenant'
import UsersPromptedForSignup, {UsersPromptedForSignup_InsertParameters} from './users_prompted_for_signup'

interface DatabaseSchema {
  managed_message: {record: ManagedMessage, insert: ManagedMessage_InsertParameters};
  player: {record: Player, insert: Player_InsertParameters};
  seed_log: {record: SeedLog, insert: SeedLog_InsertParameters};
  seed_session_log: {record: SeedSessionLog, insert: SeedSessionLog_InsertParameters};
  seeder: {record: Seeder, insert: Seeder_InsertParameters};
  server: {record: Server, insert: Server_InsertParameters};
  tenant: {record: Tenant, insert: Tenant_InsertParameters};
  users_prompted_for_signup: {record: UsersPromptedForSignup, insert: UsersPromptedForSignup_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  ManagedMessage,
  ManagedMessage_InsertParameters,
  Player,
  Player_InsertParameters,
  SeedLog,
  SeedLog_InsertParameters,
  SeedSessionLog,
  SeedSessionLog_InsertParameters,
  Seeder,
  Seeder_InsertParameters,
  Server,
  Server_InsertParameters,
  Tenant,
  Tenant_InsertParameters,
  UsersPromptedForSignup,
  UsersPromptedForSignup_InsertParameters,
}
