/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: hw/N+MQJd6tkkEjH6EdEOQXEi9O/xeBrVrgQPbshiv4e3XQClHjq8+5QDhJQvNwIJWLaU0wkxye7qskUUBf/iw==
 */

/* eslint-disable */
// tslint:disable

import Player, {Player_InsertParameters} from './player'
import SeedLog, {SeedLog_InsertParameters} from './seed_log'
import SeedSessionLog, {SeedSessionLog_InsertParameters} from './seed_session_log'
import Seeder, {Seeder_InsertParameters} from './seeder'
import Server, {Server_InsertParameters} from './server'
import ServerManagedMessage, {ServerManagedMessage_InsertParameters} from './server_managed_message'
import ServerSeeder, {ServerSeeder_InsertParameters} from './server_seeder'
import Tenant, {Tenant_InsertParameters} from './tenant'
import UsersPromptedForSignup, {UsersPromptedForSignup_InsertParameters} from './users_prompted_for_signup'

interface DatabaseSchema {
  player: {record: Player, insert: Player_InsertParameters};
  seed_log: {record: SeedLog, insert: SeedLog_InsertParameters};
  seed_session_log: {record: SeedSessionLog, insert: SeedSessionLog_InsertParameters};
  seeder: {record: Seeder, insert: Seeder_InsertParameters};
  server: {record: Server, insert: Server_InsertParameters};
  server_managed_message: {record: ServerManagedMessage, insert: ServerManagedMessage_InsertParameters};
  server_seeder: {record: ServerSeeder, insert: ServerSeeder_InsertParameters};
  tenant: {record: Tenant, insert: Tenant_InsertParameters};
  users_prompted_for_signup: {record: UsersPromptedForSignup, insert: UsersPromptedForSignup_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Player,
  Player_InsertParameters,
  SeedLog,
  SeedLog_InsertParameters,
  SeedSessionLog,
  SeedSessionLog_InsertParameters,
  Seeder,
  Seeder_InsertParameters,
  Server,
  ServerManagedMessage,
  ServerManagedMessage_InsertParameters,
  ServerSeeder,
  ServerSeeder_InsertParameters,
  Server_InsertParameters,
  Tenant,
  Tenant_InsertParameters,
  UsersPromptedForSignup,
  UsersPromptedForSignup_InsertParameters,
}
