/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 4V/gUwoVNChy7xANJTCx7y3b0I+vmnI3WB3ARdioEP+4YP0pDUvkngMSvpXQYSawnvH+MDIYUGBtm4jPU6ct/Q==
 */

/* eslint-disable */
// tslint:disable

import {ManagedMessageType} from './_enums'
import SeedSessionLog from './seed_session_log'
import Server from './server'
import Tenant from './tenant'

interface ManagedMessage {
  channel_id: bigint & {readonly __brand?: 'managed_message_channel_id'}
  message_id: bigint & {readonly __brand?: 'managed_message_message_id'}
  seed_session_id: (SeedSessionLog['id']) | null
  server_id: (Server['id']) | null
  tenant_id: Tenant['id']
  type: ManagedMessageType
}
export default ManagedMessage;

interface ManagedMessage_InsertParameters {
  channel_id: bigint & {readonly __brand?: 'managed_message_channel_id'}
  message_id: bigint & {readonly __brand?: 'managed_message_message_id'}
  seed_session_id?: (SeedSessionLog['id']) | null
  server_id?: (Server['id']) | null
  tenant_id: Tenant['id']
  type: ManagedMessageType
}
export type {ManagedMessage_InsertParameters}
