/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 56iHKlzLCkk5zlmBzWGKedDF5ONbO8UDa0I/hpaIFnej+BZT+o4D5fMw678QiHwFQR8JHP0ehSY21IcdO6A2cA==
 */

/* eslint-disable */
// tslint:disable

import Server from './server'

/**
 * a triggered seeding session
 */
interface SeedSessionLog {
  /**
   * 0 = success, 1 = failure, 2 = aborted
   */
  end_reason: (number) | null
  end_time: (Date) | null
  /**
   * @default nextval('seed_session_log_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'seed_session_log_id'}
  server_id: Server['id']
  start_time: Date
}
export default SeedSessionLog;

/**
 * a triggered seeding session
 */
interface SeedSessionLog_InsertParameters {
  /**
   * 0 = success, 1 = failure, 2 = aborted
   */
  end_reason?: (number) | null
  end_time?: (Date) | null
  /**
   * @default nextval('seed_session_log_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'seed_session_log_id'}
  server_id: Server['id']
  start_time: Date
}
export type {SeedSessionLog_InsertParameters}
