/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 9nGVl3+SW7xUI+4/F0jvR0MCDRbICd4y/PBuT55YpeTLuRsdfyqKsAWFnNm32cQXJ6u6kZEfxXyIkHGjMf+Row==
 */

/* eslint-disable */
// tslint:disable

import Player from './player'

interface Seeder {
  discord_id: bigint
  /**
   * @default nextval('seeder_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'seeder_id'}
  /**
   * 0 = 'online', 1 = 'playing', 2 = 'always' 3 = 'never'
   * 
   * @default 1
   */
  notify_when: number
  steam_id: Player['steam_id']
}
export default Seeder;

interface Seeder_InsertParameters {
  discord_id: bigint
  /**
   * @default nextval('seeder_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'seeder_id'}
  /**
   * 0 = 'online', 1 = 'playing', 2 = 'always' 3 = 'never'
   * 
   * @default 1
   */
  notify_when?: number
  steam_id: Player['steam_id']
}
export type {Seeder_InsertParameters}
