/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: xECxa6bHwwsH9F5jd5AjD39W9Ob7VX2EA0K/kVrCjsbzgKbbF5Jn4K22yFXRwAPN0hp1EsudLaBvDe7vNye9Xw==
 */

/* eslint-disable */
// tslint:disable

import Player from './player'
import SeedSessionLog from './seed_session_log'

interface SeedLog {
  /**
   * 1 = left, 2 = completed
   */
  end_reason: (number) | null
  end_time: (Date) | null
  /**
   * @default nextval('seed_log_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'seed_log_id'}
  player_id: Player['steam_id']
  seed_session_log_id: SeedSessionLog['id']
  start_time: Date
}
export default SeedLog;

interface SeedLog_InsertParameters {
  /**
   * 1 = left, 2 = completed
   */
  end_reason?: (number) | null
  end_time?: (Date) | null
  /**
   * @default nextval('seed_log_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'seed_log_id'}
  player_id: Player['steam_id']
  seed_session_log_id: SeedSessionLog['id']
  start_time: Date
}
export type {SeedLog_InsertParameters}
