/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Fum4IWgE3C32isD7ZRac8Ko0EbYMZrEdPKJcIsi3lnjlOxbtEtXDrS3l9G9G5XwIoAGMo7DW2oGFk2wpCjfowQ==
 */

/* eslint-disable */
// tslint:disable

import Server from './server'

/**
 * a triggered seeding session
 */
interface SeedSessionLog {
  /**
   * 0 = success, 1 = failure, 2 = aborted
   */
  end_reason: (number) | null
  end_time: (Date) | null
  failure_impossible: boolean
  grace_period: (number) | null
  /**
   * @default nextval('seed_session_log_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'seed_session_log_id'}
  server_id: Server['id']
  start_time: Date
}
export default SeedSessionLog;

/**
 * a triggered seeding session
 */
interface SeedSessionLog_InsertParameters {
  /**
   * 0 = success, 1 = failure, 2 = aborted
   */
  end_reason?: (number) | null
  end_time?: (Date) | null
  failure_impossible: boolean
  grace_period?: (number) | null
  /**
   * @default nextval('seed_session_log_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'seed_session_log_id'}
  server_id: Server['id']
  start_time: Date
}
export type {SeedSessionLog_InsertParameters}
