/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: +LY9biZkZeq9kBIjmv6CQl4Qp1srHlJ5BTjEPLn/CCM2Sqc40WnKnceJCO3z2SGQ6ajLfBnkswpvUGCMnd8Qhw==
 */

/* eslint-disable */
// tslint:disable

import Server from './server'

/**
 * messages relating to a particular serever, managed by our bot
 */
interface ServerManagedMessage {
  channel_id: bigint
  message_id: bigint & {readonly __brand?: 'server_managed_message_message_id'}
  /**
   * 0 = MainMessage, 1 = SeedSessionStartMessage, 2 = PlayerJoinedMessage
   */
  role: number
  server_id: Server['id']
}
export default ServerManagedMessage;

/**
 * messages relating to a particular serever, managed by our bot
 */
interface ServerManagedMessage_InsertParameters {
  channel_id: bigint
  message_id: bigint & {readonly __brand?: 'server_managed_message_message_id'}
  /**
   * 0 = MainMessage, 1 = SeedSessionStartMessage, 2 = PlayerJoinedMessage
   */
  role: number
  server_id: Server['id']
}
export type {ServerManagedMessage_InsertParameters}
