/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: FBSoNO90v3aHWk5ocUzXrQT5fykj/753Ofys8e4GMMNl0CsrNztHR6e65YVbqHTnPQSojZiB0mNIhzF7Q3rk6g==
 */

/* eslint-disable */
// tslint:disable

import Seeder from './seeder'
import Server from './server'

/**
 * joins server and seeder tables
 */
interface ServerSeeder {
  seeder_id: Seeder['id']
  server_id: Server['id']
}
export default ServerSeeder;

/**
 * joins server and seeder tables
 */
interface ServerSeeder_InsertParameters {
  seeder_id: Seeder['id']
  server_id: Server['id']
}
export type {ServerSeeder_InsertParameters}
