/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wF/MH9R3EBWb5q451Eunk9YtHylwv/ecjQBcMsaiIm80epWhJjhyMaK2lO+oTtCH144Wnkkpu+54nkZHUgUpcA==
 */

/* eslint-disable */
// tslint:disable

import Tenant from './tenant'

interface Server {
  host: string
  id: number & {readonly __brand?: 'server_id'}
  query_port: number
  seed_channel_id: string
  seed_threshold: number
  squadjs_ws_addr: string
  tenant_id: Tenant['id']
}
export default Server;

interface Server_InsertParameters {
  host: string
  id: number & {readonly __brand?: 'server_id'}
  query_port: number
  seed_channel_id: string
  seed_threshold: number
  squadjs_ws_addr: string
  tenant_id: Tenant['id']
}
export type {Server_InsertParameters}
