/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 13J0/sQp1gxjEv3VX50odfjWKrCyui05hJ9czlc9iqR96h08yOOQQMQ+7ufztS1tt0YLVv1zMYRAwUfuGVZWqA==
 */

/* eslint-disable */
// tslint:disable

import Tenant from './tenant'

interface Server {
  host: string
  id: number & {readonly __brand?: 'server_id'}
  /**
   * command friendly server label
   */
  label: string
  player_threshold_coefficient: number
  query_port: number
  seed_failed_threshold: number
  seed_start_threshold: number
  seed_success_player_count: number
  seeder_max_response_time: number
  seeder_threshold_coefficient: number
  squadjs_ws_addr: string
  tenant_id: Tenant['id']
}
export default Server;

interface Server_InsertParameters {
  host: string
  id: number & {readonly __brand?: 'server_id'}
  /**
   * command friendly server label
   */
  label: string
  player_threshold_coefficient: number
  query_port: number
  seed_failed_threshold: number
  seed_start_threshold: number
  seed_success_player_count: number
  seeder_max_response_time: number
  seeder_threshold_coefficient: number
  squadjs_ws_addr: string
  tenant_id: Tenant['id']
}
export type {Server_InsertParameters}
