/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vQ5CGVdtoLmh6SjIn4P8mhhsaN/BQEeF1oP4Ccmr10c4HDGlhsTVBGVjVFvmOSsecz7W+b14Fzyc3wv0dE6Kjg==
 */

/* eslint-disable */
// tslint:disable

interface Tenant {
  guild_id: string
  /**
   * @default nextval('tenants_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'tenant_id'}
}
export default Tenant;

interface Tenant_InsertParameters {
  guild_id: string
  /**
   * @default nextval('tenants_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'tenant_id'}
}
export type {Tenant_InsertParameters}
