/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: DjzgP5JkohKrq3QuZs+/j9CX/w3kPacFmlrmbKFUFuZuN49nhfoF9O71eCf29GsTy59vgmFi6YghFYbJO3AzPA==
 */

/* eslint-disable */
// tslint:disable

interface Tenant {
  guild_id: bigint
  /**
   * @default nextval('tenants_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'tenant_id'}
  seed_channel_id: bigint
  signup_message_id: (bigint) | null
}
export default Tenant;

interface Tenant_InsertParameters {
  guild_id: bigint
  /**
   * @default nextval('tenants_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'tenant_id'}
  seed_channel_id: bigint
  signup_message_id?: (bigint) | null
}
export type {Tenant_InsertParameters}
