/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: esDvUIiTaL+B0aHrkBQW5f1a/kALmOL1NqRYUHZ56oLn5muYZf9YNA9QJ5q6ajSpui67pzNw04fM8qSAMFTfYw==
 */

/* eslint-disable */
// tslint:disable

interface UsersPromptedForSignup {
  discord_id: (string) | null
}
export default UsersPromptedForSignup;

interface UsersPromptedForSignup_InsertParameters {
  discord_id?: (string) | null
}
export type {UsersPromptedForSignup_InsertParameters}
